baseURL = "https://blog.taq-f.space/"
languageCode = "ja"
title = "Blog"
theme = "onepress"
hasCJKLanguage = true

disqusShortname = ""
paginate = 12

[params]
    author = "taq-f"
    logo = "/images/gravatar.jpg"
    avatar = "/images/gravatar.jpg"
    # opengraphImage = "/images/onepress-logo.jpg"
    # enableRSS = true

    customCSS = false
    readMore = "Read more"
    
    # Social
    github   = "https://github.com/taq-f"

    # Widget
    widgets = true
    
    # Author box and Share button
    authorCard = false 
    # shareButton = true
    
    # Code highlighting with highlight.js
    highlightJS = true

# Taxonomies
[taxonomies]
    tag = "tags"
